version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "fastapi run /code/app/main.py --port 8000 --reload"
    ports:
      - "20800:8000"
    volumes:
      - .:/code/
    init: true
  db:
    image: postgres:15.5-alpine
    expose:
      - "5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wl
